# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  apiProject: 'Autry.DfsMovieDb/Autry.DfsMovieDb.csproj'
  testProject: 'Autry.DfsMovieDb.Tests/Autry.DfsMovieDb.Tests.csproj'
  System.Debug: 'true'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Running Tests'
  inputs:
    command: 'test'
    projects: $(testProject)
    testRunTitle: 'Running Tests'
- task: DotNetCoreCLI@2
  displayName: 'Publishing App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(apiProject)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'